version: '3.9'

services:
  # pg-database:
  #   image: postgres:15.5-alpine
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=catalog
  #     - POSTGRES_PASSWORD=catalog
  #     - POSTGRES_DB=catalog
  #     - POSTGRES_PORT=5432
  #   networks:
  #     - database-net
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: 'pg_isready -U $$POSTGRES_USER'
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis-cache:
    image: redis:7.2-alpine3.18
    restart: always
    networks:
      - cache-net
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  # app:
  #   build:
  #     context: .
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DATABASE_URL=postgresql://catalog:catalog@pg-database:5432/catalog?schema=public
  #     - REDIS_HOST=redis-cache
  #     - REDIS_PORT=6379
  #     - NPM_RUN_COMMAND=npm run start:migrate:dev
  #   networks:
  #     - database-net
  #     - cache-net
  #   depends_on:
  #     - pg-database
  #     - redis-cache

networks:
  database-net:
  cache-net:

volumes:
  pg-data:
    driver: local
  cache:
    driver: local
